export enum actions {
  FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST",
  SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST",

  ADD_TO_FAVORITES = "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVOITES = "REMOVE_FROM_FAVOITES",

  FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID",
  SET_PRODUCT_BY_ID = "SET_PRODUCT_BY_ID",
}
